Inventario/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('manual/', views.manual_usuario, name='manual_usuario'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('salir/', views.salir, name="salir"),
    path('recuperar-contraseña/', views.recuperar_contraseña, name='recuperar_contraseña'),
    path('inventario/', views.inventario),
    path('bitacora/', views.bitacora, name='bitacora'),
    path('marca/', views.marca, name='marca'),
    path('registro-marca/', views.marcaregistro, name='marcaregistro'),
    path('editar-marca/<int:marca_id>/', views.editar_marca, name='editar_marca'),
    path('eliminar-marca/<int:marca_id>/', views.eliminar_marca, name='eliminar_marca'),
    path('proveedores/', views.provedores),
    path('proveedores-registro/', views.proveedoresregistro, name="r_proveedor"),
    path('editar-proveedor/<int:proveedor_id>/', views.editar_proveedor, name='editar_proveedor'),
    path('eliminar-proveedor/<int:proveedor_id>/', views.eliminar_proveedor, name='eliminar_proveedor'),
    path('insertar/', views.registrar_item, name='insertar_r'),
    path('eliminar_registro/<int:registro_id>/', views.eliminar_registro, name='eliminar_registro'),
    path('editar_registro/<int:registro_id>/', views.editar_registro, name='editar_registro'),
    path('asignar-permisos/', views.asignar_permisos, name='asignar_permisos'),
    path('api/group-permissions/<int:group_id>/', views.get_group_permissions, name='get_group_permissions'),
    path('crear-grupo/', views.crear_grupo, name='crear_grupo'),
    path('perfil/', views.perfil, name='perfil'),
    path('cambiar-contrasena/', views.cambiar_contrasena, name='cambiar_contrasena'),
    path('acerca/', views.acerca, name='acerca'),
    path('registro/', views.registro, name='registro'),
    path('listar-items/', views.listar_items, name='listar_items'),
    path('crear-item/', views.crear_item, name='crear_item'),
    path('eliminar-item/<int:item_id>/', views.eliminar_item, name='eliminar_item'),
    path('editar-item/<int:item_id>/', views.editar_item, name='editar_item'),
    path('recetas/', views.recetas, name='recetas'),
    path('registrar-receta/', views.Recetas_registrar, name='registrar_receta'),
    path('editar-receta/<int:receta_id>/', views.editar_receta, name='editar_receta'),
    path('usar-receta/', views.usar_receta, name='usar_receta'), 
    path('eliminar-receta/<int:receta_id>/', views.eliminar_receta, name='eliminar_receta'),
    path('resumen-receta/<int:receta_id>/', views.resumen_receta, name='resumen_receta'),
    path('tipos/', views.type, name='type'), 
    path('eliminar-type/<int:id>/', views.eliminar_type, name='eliminar_type'),
    path('crear-type/', views.crear_type, name='crear_type'),
    path('editar-type/<int:id>/', views.editar_type, name='editar_type'),
    path('listar-locations/', views.listar_locations, name='listar_locations'),
    path('crear-location/', views.crear_location, name='crear_location'),
    path('editar-location/<int:location_id>/', views.editar_location, name='editar_location'),
    path('eliminar-location/<int:location_id>/', views.eliminar_location, name='eliminar_location'),
    path('cotizar-receta/<int:receta_id>/', views.cotizar_receta, name='cotizar_receta'),
    path('usos-receta/', views.lista_usos_receta, name='lista_usos_receta'),
    path('generar-reporte/', views.generar_reporte, name='generar_reporte'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

if settings.DEBUG: 
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

app/models.py
from django.db import models
from django.db.models.signals import post_save, pre_delete, post_delete, pre_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from user.models import User


class Type(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=255)
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def delete(self, *args, **kwargs):
        self._usuario = kwargs.pop('usuario', None)
        self._descripcion_personalizada = kwargs.pop('descripcion_personalizada', '')
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.nombre

class Location(models.Model):
    equipo = models.CharField(max_length=100)
    nivel = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=255)
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def delete(self, *args, **kwargs):
        self._usuario = kwargs.pop('usuario', None)
        self._descripcion_personalizada = kwargs.pop('descripcion_personalizada', '')
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.equipo


class Marca(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def delete(self, *args, **kwargs):
        self._usuario = kwargs.pop('usuario', None)
        self._descripcion_personalizada = kwargs.pop('descripcion_personalizada', '')
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.nombre

class Proveedor(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    telefono = models.CharField(max_length=20)
    correo = models.EmailField(blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def delete(self, *args, **kwargs):
        self._usuario = kwargs.pop('usuario', None)
        self._descripcion_personalizada = kwargs.pop('descripcion_personalizada', '')
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.nombre
    

class Item(models.Model):
    nombre = models.CharField(max_length=60, null=False, verbose_name='nombre')
    contenido = models.IntegerField(null=False)
    unidad_de_medida = models.CharField(max_length=30, null=False, verbose_name='unidad_medida')
    stock = models.IntegerField(default=0, blank=True)
    stock_minimo = models.IntegerField(default=0, blank=True)  # Campo agregado
    types = models.ManyToManyField(Type, related_name='items')
    locations = models.ManyToManyField(Location, related_name='items')
    marcas = models.ManyToManyField(Marca, related_name='items')
    proveedores = models.ManyToManyField(Proveedor, related_name='items')
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    pass



    def delete(self, *args, **kwargs):
        self._usuario = kwargs.pop('usuario', None)
        self._descripcion_personalizada = kwargs.pop('descripcion_personalizada', '')
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.nombre


class Registro(models.Model):
    STATUS_CHOICES = [
        (1, 'Leyenda'),
        (0, 'Descontinuado'),
    ]
        
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    cod_barras = models.CharField(max_length=100)
    no_referencia_inv = models.CharField(max_length=100)
    fecha_caducidad = models.DateField(null=True, blank=True)
    lote = models.CharField(max_length=100)
    fecha_recepcion = models.DateField()
    cantidad = models.IntegerField(blank=False, null=False)
    cod = models.CharField(max_length=100)
    status = models.IntegerField()
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2) 

    def __str__(self):
        return f'{self.item} - {self.get_status_display()}'

    def get_status_display(self):
        return dict(self.STATUS_CHOICES).get(self.status, 'Unknown')


    def save(self, *args, **kwargs):
        if self.pk is not None:
            registro_previo = Registro.objects.get(pk=self.pk)
            diferencia_cantidad = self.cantidad - registro_previo.cantidad
            self.item.stock += diferencia_cantidad
        else:
            self.item.stock += self.cantidad
        self.item.save()
        super(Registro, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.item.stock -= self.cantidad
        self.item.save()
        super(Registro, self).delete(*args, **kwargs)
        

class Receta(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    ingredientes_items = models.ManyToManyField(Item, through='RecetaItem')
    ingredientes_recetas = models.ManyToManyField('self', symmetrical=False, through='RecetaReceta', related_name='subrecetas')
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.nombre

class RecetaItem(models.Model):
    receta = models.ForeignKey(Receta, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    registro = models.ForeignKey(Registro, on_delete=models.CASCADE, null=True, blank=True)  # Temporalmente permitir nulo

    def __str__(self):
        return f'{self.cantidad} de {self.item} en {self.receta} (Registro ID: {self.registro.id if self.registro else "N/A"})'


class RecetaReceta(models.Model):
    receta = models.ForeignKey(Receta, on_delete=models.CASCADE, related_name='receta_principal')
    subreceta = models.ForeignKey(Receta, on_delete=models.CASCADE, related_name='receta_secundaria')
    cantidad = models.IntegerField()
    
    def __str__(self):
        return f'{self.cantidad} de {self.subreceta} en {self.receta}'




class UsoReceta(models.Model):
    receta = models.ForeignKey(Receta, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    cotizacion_total = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_uso = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.receta.nombre} - Usada {self.cantidad} veces el {self.fecha_uso}'



class Bitacora(models.Model):
    accion = models.CharField(max_length=50)
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    fecha_hora = models.DateTimeField(auto_now_add=True)
    modelo = models.CharField(max_length=100)
    instancia_id = models.IntegerField(null=True, blank=True)
    descripcion = models.TextField()

    @property
    def fecha(self):
        return self.fecha_hora.date()

    @property
    def hora(self):
        return self.fecha_hora.time()
    


@receiver(post_save, sender=Item)
def registrar_cambio_item(sender, instance, created, **kwargs):
    accion = 'Crear' if created else 'Actualizar'
    if created:
        Bitacora.objects.create(
            accion=accion,
            usuario=instance.usuario,
            modelo='Item',
            instancia_id=instance.id,
            descripcion=f'Se {accion.lower()} el item con ID {instance.id} y nombre {instance.nombre}'
        )

@receiver(post_delete, sender=Item)
def registrar_eliminacion_item(sender, instance, **kwargs):
    usuario = getattr(instance, '_usuario', None)
    descripcion_personalizada = getattr(instance, '_descripcion_personalizada', '')

    if usuario is None and instance.usuario:
        usuario = instance.usuario

    Bitacora.objects.create(
        accion='Eliminar',
        usuario=usuario,
        modelo='Item',
        instancia_id=instance.id,
        descripcion=descripcion_personalizada
    )
        
            
         
@receiver(post_save, sender=Marca)
def registrar_cambio_marca(sender, instance, created, **kwargs):
    if created:
        Bitacora.objects.create(
            accion='Crear',
            usuario=instance.usuario,
            modelo='Marca',
            instancia_id=instance.id,
            descripcion=f'Se creó la marca con ID {instance.id} y nombre {instance.nombre}'
        )

@receiver(post_delete, sender=Marca)
def registrar_eliminacion_marca(sender, instance, **kwargs):
    usuario = getattr(instance, '_usuario', None)
    descripcion_personalizada = getattr(instance, '_descripcion_personalizada', '')
    
    if usuario is None and instance.usuario:
        usuario = instance.usuario

    Bitacora.objects.create(
        accion='Eliminar',
        usuario=usuario,
        modelo='Marca',
        instancia_id=instance.id,
        descripcion=descripcion_personalizada
    )

@receiver(post_save, sender=Proveedor)
def registrar_cambio_provedor(sender, instance, created, **kwargs):
    if created:
        Bitacora.objects.create(
            accion='Crear',
            usuario=instance.usuario,
            modelo='Proveedor',
            instancia_id=instance.id,
            descripcion=f'Se creó el proveedor con ID {instance.id} y nombre {instance.nombre}'
        )

@receiver(post_delete, sender=Proveedor)
def registrar_eliminacion_proveedor(sender, instance, **kwargs):
    usuario = getattr(instance, '_usuario', None)
    descripcion_personalizada = getattr(instance, '_descripcion_personalizada', '')
    
    if usuario is None and instance.usuario:
        usuario = instance.usuario
    
    Bitacora.objects.create(
        accion='Eliminar',
        usuario=usuario,
        modelo='Proveedor',
        instancia_id=instance.id,
        descripcion=descripcion_personalizada
    )


    
@receiver(post_save, sender=Registro)

app/templates/locations.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ubicaciones</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/proveedor.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <ul>
                <li><a href="/perfil/">Perfil</a></li>
                <li><a href="/">Inicio</a></li>
                {%if perms.app.view_registro%}
                <li><a href="/inventario/">Inventario</a></li>
                {%endif%}
                {% if perms.app.view_receta %}
                <li><a href="/recetas/">Recetas</a></li>
                {% endif %}
                {% if perms.app.view_item %}
                <li><a href="{% url 'listar_items' %}">Items</a></li>  
                {% endif %}
                {% if perms.app.view_marca %}
                <li><a href="/marca/">Marca</a></li>
                {% endif %}
                {% if perms.app.view_proveedor %}
                <li><a href="/proveedores/">Proveedores</a></li>
                {% endif %}
                {% if perms.app.view_type %}
                <li><a href="/tipos/">Tipos</a></li>
                {% endif %}
                {% if perms.app.view_location %}
                <li><a href="/listar-locations/">Ubicaciones</a></li>
                {% endif %}
                {% if perms.app.view_bitacora %}
                <li><a href="/bitacora/">Bitácora</a></li>
                {% endif %}
                {% if perms.app.view_auth_permission %}
                <li><a href="/asignar-permisos/">Permisos</a></li>
                {% endif %}
                {% if perms.app.view_receta %}
                <li><a href="/usos-receta/">Reporte</a></li>
                {% endif %}
                <li>
                    <div class="cerrar-sesion"><a href="{% url 'salir' %}" class="cerrar-sesion">Salir</a></div>
                </li>
            </ul>
        </nav>
        <br><br><br><br>
        <h1>Ubicaciones</h1>

        {% if messages %}
            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    {% for message in messages %}
                        Swal.fire({
                            title: '{{ message.tags|capfirst }}',
                            text: '{{ message }}',
                            icon: '{{ message.tags|default:"info" }}',
                            confirmButtonText: 'Ok'
                        });
                    {% endfor %}
                });
            </script>
        {% endif %}

        {% if perms.app.add_location %}
        <button type="button" class='insertar' onclick="window.location.href='{% url 'crear_location' %}'" alt="registrar location">
            <img src="{% static 'imagenes/insertar.png' %}" class="insertar-imagen" alt="registrar location"></button>
        {% endif %}
        <table class="default">
            <thead>
                <tr>
                    <th></th>
                    <th>Id</th>
                    <th>Equipo</th>
                    <th>Nivel</th>
                    <th>Descripción</th>
                </tr>
            </thead>
            <tbody>
                {% for location in locations %}
                <tr>
                    <td>
                        {% if perms.app.change_location %}
                        <button type="button" onclick="window.location.href='{% url 'editar_location' location.id %}'" class="editar">
                            <img src="{% static 'imagenes/editar.png' %}" alt="Editar">
                        </button>
                        {% endif %}
                        <br><br>
                        {% if perms.app.delete_location %}
                        <button type="button" class="eliminar" data-location-id="{{ location.id }}">
                            <img src="{% static 'imagenes/borrar.png' %}" alt="Eliminar">
                        </button>
                        {% endif %}
                    </td>
                    <td>{{ location.id }}</td>
                    <td>{{ location.equipo }}</td>
                    <td>{{ location.nivel }}</td>
                    <td>{{ location.descripcion }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        document.querySelectorAll('.eliminar').forEach(button => {
            button.addEventListener('click', function() {
                const locationId = this.getAttribute('data-location-id');
                Swal.fire({
                    title: "¿Estás seguro de que quieres eliminarlo?",
                    text: "Este cambio no se puede revertir",
                    input: 'textarea',
                    inputLabel: 'Ingresa una descripción personalizada',
                    inputPlaceholder: 'Escribe tu descripción aquí...',
                    inputAttributes: {
                        'aria-label': 'Escribe tu descripción aquí'
                    },
                    showCancelButton: true,
                    confirmButtonColor: "#FF1401",
                    cancelButtonColor: "#458CFA",
                    confirmButtonText: "Eliminar"
                }).then((result) => {
                    if (result.isConfirmed) {
                        const csrftoken = getCookie('csrftoken');
                        const formData = new FormData();
                        formData.append('descripcion_personalizada', result.value);
                        fetch(`/eliminar-location/${locationId}/`, {
                            method: 'POST',
                            headers: {
                                'X-CSRFToken': csrftoken,
                            },
                            body: formData
                        }).then(response => {
                            if (response.ok) {
                                Swal.fire({
                                    title: "¡Eliminado!",
                                    text: "La ubicación ha sido eliminada.",
                                    icon: "success"
                                }).then(() => {
                                    window.location.reload();
                                });
                            } else {
                                Swal.fire({
                                    title: "Error",
                                    text: "No se pudo eliminar la ubicación.",
                                    icon: "error"
                                });
                            }
                        }).catch(error => {
                            console.error('Error al eliminar la ubicación:', error);
                        });
                    }
                });
            });
        });

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
    </script>
</body>
</html>

app/templates/proveedores.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Proveedores</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/proveedor.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <ul>
                <li><a href="/perfil/">Perfil</a></li>
                <li><a href="/">Inicio</a></li>
                {%if perms.app.view_registro%}
                <li><a href="/inventario/">Inventario</a></li>
                {%endif%}
                {% if perms.app.view_receta %}
                <li><a href="/recetas/">Recetas</a></li>
                {% endif %}
                {% if perms.app.view_item %}
                <li><a href="{% url 'listar_items' %}">Items</a></li>  
                {% endif %}
                {% if perms.app.view_marca %}
                <li><a href="/marca/">Marca</a></li>
                {% endif %}
                {% if perms.app.view_proveedor %}
                <li><a href="/proveedores/">Proveedores</a></li>
                {% endif %}
                {% if perms.app.view_type %}
                <li><a href="/tipos/">Tipos</a></li>
                {% endif %}
                {% if perms.app.view_location %}
                <li><a href="/listar-locations/">Ubicaciones</a></li>
                {% endif %}
                {% if perms.app.view_bitacora %}
                <li><a href="/bitacora/">Bitácora</a></li>
                {% endif %}
                {% if perms.app.view_auth_permission %}
                <li><a href="/asignar-permisos/">Permisos</a></li>
                {% endif %}
                {% if perms.app.view_receta %}
                <li><a href="/usos-receta/">Reporte</a></li>
                {% endif %}
                <li>
                    <div class="cerrar-sesion"><a href="{% url 'salir' %}" class="cerrar-sesion">Salir</a></div>
                </li>
            </ul>
        </nav>
        <br><br><br><br>
        <h1>Proveedores</h1>

        {% if messages %}
            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    {% for message in messages %}
                        Swal.fire({
                            title: '{{ message.tags|capfirst }}',
                            text: '{{ message }}',
                            icon: '{{ message.tags|default:"info" }}',
                            confirmButtonText: 'Ok'
                        });
                    {% endfor %}
                });
            </script>
        {% endif %}

        {% if perms.app.add_proveedor %}
        <button type="button" class='insertar' onclick="window.location.href='{% url 'r_proveedor' %}'" alt="registrar proveedor">
            <img src="{% static 'imagenes/insertar.png' %}" class="insertar-imagen" alt="registrar proveedor"></button>
        {% endif %}
        <table class="default">
            <thead>
                <tr>
                    <th></th>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Descripcion</th>
                    <th>Telefono</th>
                    <th>Correo</th>
                    <th>Url</th>
                </tr>
            </thead>
            <tbody>
                {% for proveedor in Proveedores %}
                <tr>
                    <td>
                        {% if perms.app.change_proveedor %}
                        <button type="button" onclick="window.location.href='{% url 'editar_proveedor' proveedor.id %}'" class="editar">
                            <img src="{% static 'imagenes/editar.png' %}" alt="Editar">
                        </button>
                        {% endif %}
                        <br><br>
                        {% if perms.app.delete_proveedor %}
                        <button type="button" class="eliminar" data-item-id="{{ proveedor.id }}">
                            <img src="{% static 'imagenes/borrar.png' %}">
                        {% endif %}
                    </td>
                    <td>{{ proveedor.id }}</td>
                    <td>{{ proveedor.nombre }}</td>
                    <td>{{ proveedor.descripcion }}</td>
                    <td>{{ proveedor.telefono }}</td>
                    <td>{% if proveedor.correo %}{{ proveedor.correo }}{% endif %}</td>
                    <td>{% if proveedor.url %}<a href="{{ proveedor.url }}" class="sin-subrayado">{{ proveedor.url }}</a>{% endif %}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        document.querySelectorAll('.eliminar').forEach(button => {
            button.addEventListener('click', function() {
                const itemId = this.getAttribute('data-item-id');
                Swal.fire({
                    title: "¿Estás seguro de que quieres eliminarlo?",
                    text: "Este cambio no se puede revertir",
                    input: 'textarea',
                    inputLabel: 'Ingresa una descripción personalizada',
                    inputPlaceholder: 'Escribe tu descripción aquí...',
                    inputAttributes: {
                        'aria-label': 'Escribe tu descripción aquí'
                    },
                    showCancelButton: true,
                    confirmButtonColor: "#FF1401",
                    cancelButtonColor: "#458CFA",
                    confirmButtonText: "Eliminar"
                }).then((result) => {
                    if (result.isConfirmed) {
                        const csrftoken = getCookie('csrftoken');
                        const formData = new FormData();
                        formData.append('descripcion_personalizada', result.value);
                        fetch(`/eliminar-proveedor/${itemId}/`, {
                            method: 'POST',
                            headers: {
                                'X-CSRFToken': csrftoken,
                            },
                            body: formData
                        }).then(response => {
                            if (response.ok) {
                                Swal.fire({
                                    title: "¡Eliminado!",
                                    text: "El proveedor ha sido eliminado.",
                                    icon: "success"
                                }).then(() => {
                                    window.location.reload();
                                });
                            } else {
                                Swal.fire({
                                    title: "Error",
                                    text: "No se pudo eliminar el proveedor.",
                                    icon: "error"
                                });
                            }
                        }).catch(error => {
                            console.error('Error al eliminar el proveedor:', error);
                        });
                    }
                });
            });
        });

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
    </script>
</body>
</html>

app/templates/recuperar_contraseña.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recuperar Contraseña</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/barra.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/recuperacion.css' %}">
</head>
<body>
    <h1>Recuperar Contraseña</h1>
    <div class="container">
        <div class="login">
            <form method="post">
                {% csrf_token %}
                <label for="email" title="Ingrese su email">correo electronico:</label>
                <input type="text" name="email" id="email" data-tooltip="Ingrese nombre de usuario">
                <label for="pregunta" title="Seleccione su pregunta de recuperación">Pregunta de recuperación:</label>
                <select name="pregunta_recuperacion" id="pregunta" data-tooltip="Seleccione pregunta de recuperación">
                    {% for opcion in opciones_pregunta_recuperacion %}
                        <option value="{{ opcion.0 }}">{{ opcion.1 }}</option>
                    {% endfor %}
                </select><br>
                <label for="respuesta" title="Ingrese su respuesta de recuperación">Respuesta de recuperación:</label>
                <input type="text" name="respuesta_recuperacion" id="respuesta" data-tooltip="Ingrese respuesta de recuperación"><br>
                <button type="submit">Recuperar Contraseña</button>
                <br>
                <label id="mensaje">{% if mensaje %}{{ mensaje }}{% endif %}</label>
            </form>
        </div>
    </div>
    <div class="navbar">
        <ul>
            <li><a href="/">Inicio</a></li>
            <li><a href="/acerca/">Acerca de</a></li>
            <li><a href="http://www.uusmb.unam.mx/">Página de la Unidad</a></li>
            <li><a href="{% static 'pdf/sistema.pdf' %}" download>Manual de Usuario</a></li>
        </ul>
    </div>
</body>
</html>